- en: 'Enhanced Debugging in Python: Tracebacks Just Got a Major Upgrade'
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Python 中的增强调试：追溯信息获得重大升级
- en: 原文：[https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38](https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38](https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38)
- en: How location-enriched tracebacks facilitate the debugging experience in Python
    3.11
  id: totrans-2
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 位置丰富的追溯信息如何促进 Python 3.11 中的调试体验
- en: '[](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[![Thomas
    A Dorfer](../Images/9258a1735cee805f1d9b02e2adf01096.png)](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)[![Towards
    Data Science](../Images/a6ff2676ffcc0c7aad8aaf1d79379785.png)](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    [Thomas A Dorfer](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)'
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: '[](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[![Thomas
    A Dorfer](../Images/9258a1735cee805f1d9b02e2adf01096.png)](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)[![Towards
    Data Science](../Images/a6ff2676ffcc0c7aad8aaf1d79379785.png)](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    [Thomas A Dorfer](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)'
- en: ·Published in [Towards Data Science](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    ·4 min read·Mar 15, 2023
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: ·发表于 [Towards Data Science](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    ·4 分钟阅读·2023年3月15日
- en: --
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: --
- en: '![](../Images/b7116c89ccd139a962a51f3ddcada150.png)'
  id: totrans-6
  prefs: []
  type: TYPE_IMG
  zh: '![](../Images/b7116c89ccd139a962a51f3ddcada150.png)'
- en: Photo by [Mohamed Hassan](https://pixabay.com/users/mohamed_hassan-5229782/)
    on [Pixabay](https://pixabay.com/vectors/error-warning-computer-crash-6641731/)
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 图片来源 [Mohamed Hassan](https://pixabay.com/users/mohamed_hassan-5229782/) 于 [Pixabay](https://pixabay.com/vectors/error-warning-computer-crash-6641731/)
- en: In Python, a traceback is a report that is displayed when an exception occurs,
    along with a (hopefully) helpful error message that can guide the user to the
    problem.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 在 Python 中，追溯信息是在发生异常时显示的报告，以及一个（希望）有帮助的错误消息，可以引导用户找到问题所在。
- en: Up until now, tracebacks only showed the line in which the exception occurred,
    but did not provide any location-specific information about which part of that
    line is affected.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 到目前为止，追溯信息仅显示了异常发生的行，但没有提供关于该行的具体位置的信息。
- en: 'To illustrate this, let’s assume we have a dictionary object containing some
    summary statistics about some random data. Based on that, we’d like to calculate
    the lower and upper bounds of the confidence interval. This can be done as follows:'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 为了说明这一点，假设我们有一个字典对象，包含一些随机数据的总结统计信息。基于此，我们希望计算置信区间的下限和上限。可以按如下方式进行：
- en: '[PRE0]'
  id: totrans-11
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: 'I deliberately assigned `None` to the *z*-value in our dictionary object to
    provoke an exception. For Python versions lower than 3.11, this is what the traceback
    would look like:'
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 我故意将`None`赋值给我们字典对象中的*z*值，以引发异常。对于低于 3.11 的 Python 版本，追溯信息将如下所示：
- en: '![](../Images/37d091ac41cbf5f6201da656215fa970.png)'
  id: totrans-13
  prefs: []
  type: TYPE_IMG
  zh: '![](../Images/37d091ac41cbf5f6201da656215fa970.png)'
- en: Image by the Author.
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 作者提供的图像。
- en: While it correctly shows the line where the exception occurred, the user is
    not given any information about whether the issue lies with the mean, the *z*-value,
    the standard deviation, or the sample size *n*.
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: 虽然它正确地显示了异常发生的行，但用户没有获得关于问题是否出在均值、*z*值、标准差或样本大小*n*的任何信息。
- en: 'This has changed in Python 3.11 with its new, location-enriched traceback feature:'
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: 这在 Python 3.11 中发生了变化，新增了位置丰富的追溯信息功能：
- en: '![](../Images/63d6934a4f43948f011a8d99cac96217.png)'
  id: totrans-17
  prefs: []
  type: TYPE_IMG
  zh: '![](../Images/63d6934a4f43948f011a8d99cac96217.png)'
- en: Image by the Author.
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: 作者提供的图像。
- en: Here, it clearly highlights that the error occurred with the term `stats['z']`,
    making it a lot easier for the user to debug the program.
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: 在这里，它清楚地突出显示了错误发生在术语`stats['z']`上，使用户调试程序变得容易得多。
- en: Let’s now look at another example. Imagine you have a Python script that performs
    some computation on matrices. Remember, with matrix multiplication, the inner
    dimensions must be the same. In other words, the number of columns in the first
    matrix must be the same as the number of rows in the second matrix.
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
- en: In the code below, I introduced a dimension mismatch between matrices `c` and
    `d`.
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  id: totrans-22
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: 'As expected, this results in an exception when trying to multiply them. Here’s
    what it looks like in Python versions lower than 3.11:'
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
- en: '![](../Images/0d0cd7492b1ef0156393c853a561ea49.png)'
  id: totrans-24
  prefs: []
  type: TYPE_IMG
- en: Image by the Author.
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
- en: If this code was part of a larger program, or involved more matrices, it would
    be very difficult and time-consuming to figure out which matrix is the one with
    the incorrect dimensions.
  id: totrans-26
  prefs: []
  type: TYPE_NORMAL
- en: In Python 3.11, the traceback pinpoints to the exact part in the formula that
    contains the matrices whose dimensions mismatch, guiding the user directly to
    the core of the issue.
  id: totrans-27
  prefs: []
  type: TYPE_NORMAL
- en: '![](../Images/af0561403d2574444a36d8e3008f2249.png)'
  id: totrans-28
  prefs: []
  type: TYPE_IMG
- en: Image by the Author.
  id: totrans-29
  prefs: []
  type: TYPE_NORMAL
- en: Location-enriched tracebacks considerably facilitate the programmer’s debugging
    experience and can lead to speedier resolutions when faced with bugs in the code.
    In order to enable this feature, however, one has to update Python to [version
    3.11](https://www.python.org/downloads/release/python-3110/).
  id: totrans-30
  prefs: []
  type: TYPE_NORMAL
- en: I hope this feature will make your debugging experience easier and save you
    some valuable time while doing so. Happy coding!
  id: totrans-31
  prefs: []
  type: TYPE_NORMAL
- en: 'More Resources:'
  id: totrans-32
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[What’s New In Python 3.11 — Python 3.11.2 documentation](https://docs.python.org/3/whatsnew/3.11.html#new-features)'
  id: totrans-33
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Liked this article?
  id: totrans-34
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Let’s connect! You can find me on [Twitter](https://twitter.com/ThomasADorfer)
    and [LinkedIn](https://www.linkedin.com/in/thomasdorfer/).
  id: totrans-35
  prefs: []
  type: TYPE_NORMAL
- en: If you like to support my writing, you can do so through a [Medium Membership](https://thomasdorfer.medium.com/membership),
    which provides you access to all my stories as well as those of thousands of other
    writers on Medium.
  id: totrans-36
  prefs: []
  type: TYPE_NORMAL
- en: '[](https://medium.com/@thomasdorfer/membership?source=post_page-----bd77fb32db38--------------------------------)
    [## Join Medium with my referral link - Thomas A Dorfer'
  id: totrans-37
  prefs: []
  type: TYPE_NORMAL
- en: Read every story from Thomas A Dorfer (and thousands of other writers on Medium).
    Your membership fee directly supports…
  id: totrans-38
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: medium.com](https://medium.com/@thomasdorfer/membership?source=post_page-----bd77fb32db38--------------------------------)
  id: totrans-39
  prefs: []
  type: TYPE_NORMAL
