- en: 'Enhanced Debugging in Python: Tracebacks Just Got a Major Upgrade'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 原文：[https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38](https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: How location-enriched tracebacks facilitate the debugging experience in Python
    3.11
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[![Thomas
    A Dorfer](../Images/9258a1735cee805f1d9b02e2adf01096.png)](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)[![Towards
    Data Science](../Images/a6ff2676ffcc0c7aad8aaf1d79379785.png)](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    [Thomas A Dorfer](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)'
  prefs: []
  type: TYPE_NORMAL
- en: ·Published in [Towards Data Science](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    ·4 min read·Mar 15, 2023
  prefs: []
  type: TYPE_NORMAL
- en: --
  prefs: []
  type: TYPE_NORMAL
- en: '![](../Images/b7116c89ccd139a962a51f3ddcada150.png)'
  prefs: []
  type: TYPE_IMG
- en: Photo by [Mohamed Hassan](https://pixabay.com/users/mohamed_hassan-5229782/)
    on [Pixabay](https://pixabay.com/vectors/error-warning-computer-crash-6641731/)
  prefs: []
  type: TYPE_NORMAL
- en: In Python, a traceback is a report that is displayed when an exception occurs,
    along with a (hopefully) helpful error message that can guide the user to the
    problem.
  prefs: []
  type: TYPE_NORMAL
- en: Up until now, tracebacks only showed the line in which the exception occurred,
    but did not provide any location-specific information about which part of that
    line is affected.
  prefs: []
  type: TYPE_NORMAL
- en: 'To illustrate this, let’s assume we have a dictionary object containing some
    summary statistics about some random data. Based on that, we’d like to calculate
    the lower and upper bounds of the confidence interval. This can be done as follows:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: 'I deliberately assigned `None` to the *z*-value in our dictionary object to
    provoke an exception. For Python versions lower than 3.11, this is what the traceback
    would look like:'
  prefs: []
  type: TYPE_NORMAL
- en: '![](../Images/37d091ac41cbf5f6201da656215fa970.png)'
  prefs: []
  type: TYPE_IMG
- en: Image by the Author.
  prefs: []
  type: TYPE_NORMAL
- en: While it correctly shows the line where the exception occurred, the user is
    not given any information about whether the issue lies with the mean, the *z*-value,
    the standard deviation, or the sample size *n*.
  prefs: []
  type: TYPE_NORMAL
- en: 'This has changed in Python 3.11 with its new, location-enriched traceback feature:'
  prefs: []
  type: TYPE_NORMAL
- en: '![](../Images/63d6934a4f43948f011a8d99cac96217.png)'
  prefs: []
  type: TYPE_IMG
- en: Image by the Author.
  prefs: []
  type: TYPE_NORMAL
- en: Here, it clearly highlights that the error occurred with the term `stats['z']`,
    making it a lot easier for the user to debug the program.
  prefs: []
  type: TYPE_NORMAL
- en: Let’s now look at another example. Imagine you have a Python script that performs
    some computation on matrices. Remember, with matrix multiplication, the inner
    dimensions must be the same. In other words, the number of columns in the first
    matrix must be the same as the number of rows in the second matrix.
  prefs: []
  type: TYPE_NORMAL
- en: In the code below, I introduced a dimension mismatch between matrices `c` and
    `d`.
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
- en: 'As expected, this results in an exception when trying to multiply them. Here’s
    what it looks like in Python versions lower than 3.11:'
  prefs: []
  type: TYPE_NORMAL
- en: '![](../Images/0d0cd7492b1ef0156393c853a561ea49.png)'
  prefs: []
  type: TYPE_IMG
- en: Image by the Author.
  prefs: []
  type: TYPE_NORMAL
- en: If this code was part of a larger program, or involved more matrices, it would
    be very difficult and time-consuming to figure out which matrix is the one with
    the incorrect dimensions.
  prefs: []
  type: TYPE_NORMAL
- en: In Python 3.11, the traceback pinpoints to the exact part in the formula that
    contains the matrices whose dimensions mismatch, guiding the user directly to
    the core of the issue.
  prefs: []
  type: TYPE_NORMAL
- en: '![](../Images/af0561403d2574444a36d8e3008f2249.png)'
  prefs: []
  type: TYPE_IMG
- en: Image by the Author.
  prefs: []
  type: TYPE_NORMAL
- en: Location-enriched tracebacks considerably facilitate the programmer’s debugging
    experience and can lead to speedier resolutions when faced with bugs in the code.
    In order to enable this feature, however, one has to update Python to [version
    3.11](https://www.python.org/downloads/release/python-3110/).
  prefs: []
  type: TYPE_NORMAL
- en: I hope this feature will make your debugging experience easier and save you
    some valuable time while doing so. Happy coding!
  prefs: []
  type: TYPE_NORMAL
- en: 'More Resources:'
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[What’s New In Python 3.11 — Python 3.11.2 documentation](https://docs.python.org/3/whatsnew/3.11.html#new-features)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Liked this article?
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Let’s connect! You can find me on [Twitter](https://twitter.com/ThomasADorfer)
    and [LinkedIn](https://www.linkedin.com/in/thomasdorfer/).
  prefs: []
  type: TYPE_NORMAL
- en: If you like to support my writing, you can do so through a [Medium Membership](https://thomasdorfer.medium.com/membership),
    which provides you access to all my stories as well as those of thousands of other
    writers on Medium.
  prefs: []
  type: TYPE_NORMAL
- en: '[](https://medium.com/@thomasdorfer/membership?source=post_page-----bd77fb32db38--------------------------------)
    [## Join Medium with my referral link - Thomas A Dorfer'
  prefs: []
  type: TYPE_NORMAL
- en: Read every story from Thomas A Dorfer (and thousands of other writers on Medium).
    Your membership fee directly supports…
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: medium.com](https://medium.com/@thomasdorfer/membership?source=post_page-----bd77fb32db38--------------------------------)
  prefs: []
  type: TYPE_NORMAL
